Kommunicate-io/KommunicateChatUI-iOS-SDK

CHANGELOG.md
KommunicateChatUI-iOS-SDK.podspec
Sources/Utilities/UI+Style.swift
Sources/Views/ALKChatBar.swift

ALK Chat Bar Place Holder was not changing the direction for RTL Languages. When we set the RTL as device language & open the app, the place holder direction has not changed.
Tested Locally for both LTR & RTL languages, its changing the direction.

[CM-739] iOS SDK | RTL support for sign-in page and text bar in chat page.

---

CHANGELOG.md
Demo/Podfile
Demo/Podfile.lock
Sources/Utilities/ALKHTTPManager.swift
Sources/ViewModels/ALKConversationViewModel.swift
Sources/Views/ALKAttatchmentView.swift
Sources/Views/ALKVideoCell.swift

- Added s3 support for upload & download attachments
Locally tested by uploading images & checking the URLs.

[CM-842] Add support for s3 service for attachment & make it as default | iOS SDK

---

Sources/Views/ALKPhotoCell.swift
Sources/Views/ALKVideoCell.swift

- When image sent from web chat widget,, it has some spaces.due to this, thumbnail was not showing.
- When video sent form web chat widget, thumbnailBlobKey coming as nil.
Fixed above issues by checking for nil & removing the space before creating downloadURL.

[CM-773] Fix for thumbnail blobkey(empty, spaces) issue

---

CHANGELOG.md
Demo/Podfile.lock
Sources/Controllers/ALKConversationViewController+TableView.swift
Sources/Views/ALKChatCell.swift

- Added localisation support for label which will be shown on conversation list screen.(the value will be based on the last message of conversation

[CM-848] Added localisation support for last message(shown on conversation list screen)

---

Sources/ViewModels/ALKConversationViewModel.swift

- SDK throws fatal error when open a conversation which doesn't have welcome message
- Fixed it by checking message length in the api call
- Locally tested by checking both scenarios

Fixed Typing Indicator Crash when Welcome message is not configured 

---

RichMessageKit/Utilities/RMCellConfiguration.swift
RichMessageKit/Views/ReceivedButtonsCell.swift
RichMessageKit/Views/ReceivedFAQMessageCell.swift
RichMessageKit/Views/ReceivedImageMessageCell.swift
Sources/Controllers/ALKConversationViewController.swift

- KMCellConfiguration file is throwing error when it gets called from `Richmessagekit` module files in lib lint
- When I observed codes we are maintaining separate set of files for `Richmessagekit` configuration for themes, font etc
- Followed the same way created a new class called `RMCellConfiguration` to maintain the configuration for `Richmessage` cells

Fixed lib lint KMCellConfiguration scope issue

---

CHANGELOG.md
KommunicateChatUI-iOS-SDK.podspec
RichMessageKit/Utilities/SuggestedReplyViewSizeCalculator.swift

- Last button in Suggested Reply Buttons list is not supporting multiple lines due lack of height provided for the cell
Issue: 
Fix:

[CM-979] Suggested Reply/ Curved  Button is not supporting multiple lines

---

CHANGELOG.md
Demo/Podfile.lock
KommunicateChatUI-iOS-SDK.podspec
Sources/Controllers/ALKConversationViewController.swift
Sources/ViewModels/ALKConversationViewModel.swift

- Typing indicator delay is showing for older conversation messages when we fetch through api ..Fixed it by comparing created time with current time.
-  Stopped typing timer while exiting the Conversation Screen.

[CM-977] Fix for typing indicator shown for older conversation when it fetched through api call

---

CHANGELOG.md
KommunicateChatUI-iOS-SDK.podspec
Sources/Controllers/ALKMediaViewerViewController.swift

- GIF images are not playing when it expanded to full screen mode in the conversation
Bug:
https://user-images.githubusercontent.com/61688116/182768833-020fecec-b9c4-412e-ad0f-cc48a4746706.mov
After Fix: 
https://user-images.githubusercontent.com/61688116/182768820-0a0689ba-b4f3-42a8-b3a1-3aea2ba2cb27.mov

[CM-945] Gif not playing in conversations when opened

---

CHANGELOG.md
Sources/Views/ALKInformationCell.swift

- Fixed the Rated Feedback View in iOS SDK
- Fixed with ideal solution so that it won't create any problem in Agent App as well.
**Issue:**
**After Fix:**
This issue found while doing the sanity testing for iOS SDK

Fixed Rating Feedback View issue

---

CHANGELOG.md
Sources/Controllers/ALKConversationViewController+TableView.swift
Sources/Views/ALKChatBaseCell.swift
Sources/Views/ALKLinkPreviewBaseCell.swift
Sources/Views/ALKMessageBaseCell.swift

-  Added LongPress Gesture for LinkMessages
- In Existing version if user sends, receives message which contains link, they can't copy that link by longpress it.
Existing:
https://user-images.githubusercontent.com/61688116/183840733-a8f304f7-f685-4c5e-a084-23668f72b812.mov
After this fix:
https://user-images.githubusercontent.com/61688116/183840688-7453fa37-8e11-40b8-8a74-2b07e0ab3c4b.mov

[CM-960] Added LongPress Gesture for LinkMessages

---

CHANGELOG.md
Sources/Models/ALKConfiguration.swift

- Remove default reply option from Message Info menu

[CM-998] - Remove default Reply option

---

Sources/Controllers/ALKConversationViewController.swift

- Instead of observing notifications in KMConversationViewController , handled `didBecomeActiveNotification` & mqtt's `userOnlineStatusChanged`  (At ALKConversationViewController) in a way that sub class (KMConversationViewController) can get these notifications.
Linked PR in KM-iOS-SDK : https://github.com/Kommunicate-io/Kommunicate-iOS-SDK/pull/227#pullrequestreview-1081902653

[CM-894] Added methods for updating online/offline status in realtime

---

Sources/Utilities/ALMessage+Extension.swift

- agent app is crashed when checking the attachment type using the prefix
- Added a nil check for the content type of file meta to fix the crash as couldn't reproduce the issue for all attachment combinations.

[CM-888] iOS Firebase crash | ALMessage+Extension.swift line 360 

---

Sources/Controllers/ALKConversationViewController.swift

- Form template messages getting cropped when it is arrived
- refreshing the form again for second is cropping the the form. We are refreshing the cell again if its form message, its causing the issue. So removing the refreshing flow

[CM-1156] Fixed form issue for small  devices

---

Sources/Utilities/RatingHelper.swift

- Without  ` import UIKit` causing Build issue on UIImages on RatingHelper.swift file when integrate through SPM only
- Tested it after this fix by pointing to the commit hash in a Sample SPM App
- To avoid issues like this in future, adding sample SPM app in bitrise & its build will be verified before every release in iOS SDK.

SPM Integration Build Issue

---

Demo/Podfile
Demo/Podfile.lock
Sources/Controllers/ALKConversationViewController.swift
Sources/Utilities/KMZendeskChatHandler.swift

- Added authentication with jwt for zendesk user
- optimized handoff flow
- updated zendesk intialization flow & connection to zendesk server
- Added message buffer for failed messages incase of zendesk connection lost
- Handled the chat logs for agent messages
New Conversation Flow:
1. Once conversation created, zendesk will be intialized (only for Zendesk users) and users will be authenticated. 
2. when handoff happens , zendeskhandler will start to process user messages to zendesk.
Existing Conversation Flow:
1. While opening the existing conversation, assignee will be checked & handoff flag will be updated accordingly
2. Users will be authenticated & will start observing chat logs(Chat Events). if any new log(message, event) is there , that log will be processed.

[CM-1217] Zendesk Authentication & Chat Session

---

Demo/Podfile
Demo/Podfile.lock
Sources/Utilities/KMZendeskChatHandler.swift

- Observe events -> message, attachment message, agent leave
- Added chat log logic to sync zendesk and kommunicate messages
- When message event triggered, send message to /rest/ws/zendesk/message/send
- When attachment event triggered, send attachment to /rest/ws/zendesk/file/send
- When Agent ends chat from Zendesk, call Resolve conversation API and resolve the conversation.
- When "Restart conversation" is clicked, a new conversation is created to maintain a single chat thread.
- Handled Chat logs -> If the app is closed and opened again, it will sync the messages sent from Zendesk dashboard until session is live

[CM-1191] Observe Zendesk Chat Events

---

Sources/Controllers/ALKConversationViewController.swift
Sources/Models/FormTemplate.swift
Sources/ViewModels/ALKConversationViewModel.swift

- Added support to send hidden message
- Added support for metadata for Action Message on Form Template
- Added Support for hiding message on form submission based on metadata
- if metadata contains `  "category": "HIDDEN"` submission message will be hidden on user end. it will be visible on dashboard
You can see` submitted my details` only visible at dashboard end not at user end

[CM-1325] Hide User submitted message on form submission 

---

CHANGELOG.md
Demo/KommunicateChatUI-iOS-SDK-Demo.xcodeproj/project.pbxproj
Demo/Podfile.lock
KommunicateChatUI-iOS-SDK.podspec
Package.resolved
Package.swift
Sources/Utilities/KMZendeskChatHandler.swift
Sources/Utilities/UIApplication+Extension.swift

- Zendesk dependency was not added on Package.swift.So its creating problem when Kommunicate sdk integrated via SPM.
- Removed extra libraries added by zendesk pack. integrated required chatproviders in pod as well as package.
- Tested by adding this  in sample app by SPM.

Fixed Build Issue on SPM  Integration 

---

CHANGELOG.md
Sources/Models/ALKConfiguration.swift

- Added Customisation flag `hideChatInHelpcenter` to hide/show the chat widget on helpcenter/FAQ page

[CM-1355] Added customisation flag for hiding chat widget on helpcenter page

---

Demo/Podfile.lock
KommunicateChatUI-iOS-SDK.podspec
Package.resolved
Package.swift

- Current Chat UI is contains Kingfisher(v-7.0.0) sub pod. But kingfisher library has creating build [issue](https://github.com/onevcat/Kingfisher/pull/2029) on Xcode 14.2. This issue was fixed on version[ 7.6.1](https://github.com/onevcat/Kingfisher/releases/tag/7.6.1). So pointing to the latest version of kingfisher
- Tested all the instances(40 places) of kingfisher usage in our sdk.

updated kingfisher pod

---

CHANGELOG.md
Sources/Controllers/ALKConversationViewController.swift
Sources/Models/ALKConfiguration.swift

- Fixed Form submitted data double stringified on Api and matched with web, android sdk by removing kmchatcontext in the request data
- Added support to  Form action & postformdataasmessage at the same time
- Added customisation for pushing web view after receiving response from formation url.
-

[CM-1415] Form Template Submission Issues

---

CHANGELOG.md
Sources/Controllers/ALKConversationViewController+DocumentManager.swift
Sources/Controllers/ALKConversationViewController.swift
Sources/Resources/Base.lproj/Localizable.strings
Sources/Utilities/ALKFileUtils.swift
Sources/Utilities/SystemMessage.swift

- Added support for restriction  upload attachments based on size. By default it is 25 MB. it can be customized based by using below code
```
ALApplozicSettings.setMaxImageSizeForUploadInMB(6)
```
you should import communicate core module whenever you use this customisation like this `import KommunicateCore_iOS_SDK`

Added support for restriction for attachment based on size

---

Sources/Controllers/ALKConversationViewController.swift
Sources/Models/ALKConfiguration.swift
Sources/Utilities/ALKHTTPManager.swift
Sources/Utilities/ALKVideoUploadManager.swift
Sources/Utilities/ALMessage+Extension.swift
Sources/ViewModels/ALKConversationViewModel.swift

- Fixed upload issue taxbuddy server was not able to detect the group id and hence uploading docs are not routed correctly on their side
- Added a flag to to restrict opening browser when link list template item tapped
- Media event is not getting triggered from the server due to content type.Fixed it by changing the content type to 1(attachment) and handled it in the UI

[CM-1479] Fixed upload issue

---

CHANGELOG.md
Sources/Controllers/ALKConversationViewController.swift
Sources/Views/ALKTemplateMessagesView.swift

- Fixed Template Message views issue
- Moved template button to centre of the screen

[CM-1451] Fixed template message view issue

---

Sources/Utilities/KMConversationScreenConfiguration.swift
Sources/ViewModels/ALKConversationViewModel.swift

- Added support for showing typing indicator while webhook is fetching the response.
- We can't achieve this via bot delay configuration.Because delay is will be added once message/response reached the sdk on front end. 
- This will be useful when webhook itself is taking 3-4 seconds to respond .
- This can be enabled by using `KMConversationScreenConfiguration.showTypingIndicatorWhileFetchingResponse = true` . By default it is false.

[CM-1454] Added Support for showing Typing Indicator while bot feching the response

---

Sources/Utilities/UIColor+Extension.swift

- The issue was the colour of app bar is grey at initial registration 
- Previously the colour hex code for the navigationOceanBlue was  "ECEFF1"
- Changed the color hex code for the navigationOceanBlue with  "0076FF"
- After changing the color its working fine

[CM-1525] Change in color code of navigationOceanBlue

---

CHANGELOG.md
Sources/Controllers/ALKConversationViewController.swift
Sources/Controllers/ALKMultipleLanguageSelectionViewController.swift
Sources/Models/ALKConfiguration.swift
Sources/Models/KMLanguage.swift

- Added support to trigger an intent when language is selected for speech to text
- Created KMLanguage class to use it on Multiple Language support for Speech to Text
- This is can be enabled like below
```
let langs: [KMLanguage] = [KMLanguage(code: "hi", name: "Hindi",sendMessageOnClick: true, messageToSend: "hindi"), KMLanguage(code: "en-US", name: "English"), KMLanguage(code: "zh-hans", name: "Mandarin"), KMLanguage(code: "ms", name: "Malaysian")]
// To enable it pass the list like this 
Kommunicate.defaultConfiguration.languagesForSpeechToText = langs
```
- You can observe after Hindi selected , a message say "Hindi" was sent and conversation assigned to Hindi bot.

[CM-1523] Added support to trigger an intent when language is selected for Speech to Text

---

CHANGELOG.md
Sources/Controllers/ALKConversationViewController.swift

- Added a condition to check the message is visible in screen or not on basis of that the down arrow will appear 
- This issue was coming only when the bot reply time is set to 0.0 sec.

[CM-1558] Fixed down arrow coming in bottom of the screen when welcome message get rendered 

---

CHANGELOG.md
Sources/Views/ALKFormCell.swift
Sources/Views/ALKFriendFormCell.swift

-  Added border to form. Colour code is similar to the android form border.
-  Removed the padding from the top of the cell but this is only available for iOS 15 and above. Tried multiple ways to remove the padding but only this method worked.
-  Removed the trailing anchor of submit button. This was stretching the button frame earlier.

[CM-1569] Fixed the Form Mismatch.

---

Sources/Controllers/ALKMultipleLanguageSelectionViewController.swift
Sources/Controllers/KMBottomSheetcontroller.swift
Sources/Views/KMLanguageView.swift

- improved the UI of language selection for speech to text
- made it similar to android bottom sheet instead of presenting screen
- provided customization for curtain items
##SS

[CM-1538] Improved UI of multiple language selection & make it similar to android

---

CHANGELOG.md
Sources/Utilities/ALKHTTPManager.swift
Sources/Utilities/ALKVideoUploadManager.swift
Sources/Utilities/ALMessage+Extension.swift
Sources/ViewModels/ALKConversationViewModel.swift

Added a null check for the `ALApplozicSettings.getDefaultOverrideuploadUrl()` inside `ALMessage+Extension.swift`

[CM-1590] Crash fix while updating agent app to the latest ios sdk

---

Sources/Controllers/ALKConversationViewController.swift

File size in KB was being tested with maximumAttachmentSize which was in MB so converted maximumAttachmentSize to KB as well

Fixed video not sending

---

Sources/Utilities/ALKHTTPManager.swift

- image Uploaded from iOS not getting downloaded on Android Agent App & Dashboard
- It was created from the last release. Fixed the wrong check code

fixed image upload prod issue

---

CHANGELOG.md
Sources/Controllers/ALKCreateGroupViewController.swift
Sources/Controllers/ALKReplyController.swift
Sources/Views/ALKAddParticipantCollectionCell.swift
Sources/Views/ALKChatCell.swift
Sources/Views/ALKConversationNavBar.swift
Sources/Views/ALKFriendCell.swift
Sources/Views/ALKFriendContactCell.swift
Sources/Views/ALKFriendDocumentCell.swift
Sources/Views/ALKFriendFormCell.swift
Sources/Views/ALKFriendGenericCardMessageCell.swift
Sources/Views/ALKFriendLinkPreviewCell.swift
Sources/Views/ALKFriendLocationCell.swift
Sources/Views/ALKFriendMessageCell.swift
Sources/Views/ALKFriendMessageQuickReplyCell.swift
Sources/Views/ALKFriendNewChatCell.swift
Sources/Views/ALKFriendPhotoCell.swift
Sources/Views/ALKFriendVideoCell.swift
Sources/Views/ALKFriendVoiceCell.swift
Sources/Views/ALKGroupMemberCell.swift
Sources/Views/ALKLinkView.swift
Sources/Views/ALKListTemplateCell.swift
Sources/Views/ALKMessageButtonCell.swift
Sources/Views/MentionAutoCompleteCell.swift

ImageResource of KingFisher was conflicting with Xcode's GeneratedAssetSymbols.ImageResource, hence renamed the `ImageResource` as `Kingfisher.ImageResource`. Check the issue [here.](https://github.com/onevcat/Kingfisher/issues/2114)
I tried to build with Xcode 14 as well as XCode 15 beta 8 and the app was building successfully

[CM-1629] Added support for XCode 15 beta 8

---

CHANGELOG.md
Sources/Controllers/ALKConversationListTableViewController.swift
Sources/ViewModels/ALKConversationListViewModel.swift

- Called update message list after every delete of the message.
- Removed the delay of showing the delete conversation alert.
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/55034aa9-ca51-4474-b982-a1689291b102

[CM-1567] Fixed After deleting the last conversation on conversation list screen & empty state should be shown 

---

CHANGELOG.md
Sources/Controllers/ALKAccountSuspensionController.swift
Sources/Controllers/ALKConversationListViewController.swift
Sources/Controllers/ALKConversationViewController.swift

- used the function isModalInPresentation to remove the swipe to close functionality. (by default it is false)
- hide the close button.
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/8b829b29-f6ef-4410-b25b-2f0cdc4c24fd

[CM-1616] Fixed Trial Period Alert closable issue.

---

CHANGELOG.md
Sources/Views/ALKChatBar.swift

Fixed "kommunicate.io" showing in iOS 17 even when "powered by kommunicate.io" should be disabled

[CM-1647] Disabled kommunicate.io showing in iOS 17

---

CHANGELOG.md
Sources/Controllers/ALKConversationViewController+TableView.swift
Sources/Models/ALKConfiguration.swift
Sources/Views/ALKMessageBaseCell.swift

Earlier links were showing in blue color and as by default we have violet color as sent message background color so the link was not visible to the end user. Hence we changed it to white to make it look readable.

[CM-1636] Changed foreground color for links 

---

CHANGELOG.md
RichMessageKit/Views/core/SuggestedReplyView.swift

- Spacing in UIStackView are creating this issue when less than three subviews are passing.
- Created a new UIStackView conversion function with no spacing.
- added a check for subviews to pass evenly to horizontalStackView and horizontalStackViewWithSpace.
**Before Changes (iPhone 7 / IPhone 15 Pro Max)**
**After Changes (iPhone 7 / IPhone 15 Pro Max)**

[CM- 1315] Button Lengthy title support not working on iPhone 7

---

CHANGELOG.md
Sources/ViewModels/ALKConversationViewModel.swift

- Users were not able to fetch only first few messages which is fixed now

[CM-1652] Fixed conversation history mismatch

---

Sources/Controllers/ALKConversationViewController.swift

- Fixed Submit Rich Message Button tap issue when form action details is not there in payload.

[CM-1665] Submit RM Button Tap issue

---

RichMessageKit/Themes/ImageBubbleStyle.swift
RichMessageKit/Themes/MessageStyle.swift
RichMessageKit/Utilities/UIColor+ExtensionDarkMode.swift
RichMessageKit/Views/core/CurvedImageButton.swift
Sources/Controllers/ALKBaseNavigationController.swift
Sources/Controllers/ALKConversationListTableViewController.swift
Sources/Controllers/ALKConversationViewController.swift
Sources/Controllers/ALKCustomPickerViewController.swift
Sources/Controllers/ALKFormDatePickerViewController.swift
Sources/Controllers/ALKMapViewController.swift
Sources/Controllers/ALKMultipleLanguageSelectionViewController.swift
Sources/Models/ALKConfiguration.swift
Sources/Utilities/Message+Style.swift
Sources/ViewModels/KMConversationInfoViewModel.swift
Sources/Views/ALKChatBar.swift
Sources/Views/ALKChatCell.swift
Sources/Views/ALKFormCell.swift
Sources/Views/ALKFormDateItemCell.swift
Sources/Views/ALKFormMultiSelectItemCell.swift
Sources/Views/ALKFormPasswordItemCell.swift
Sources/Views/ALKFormSingleSelectItemCell.swift
Sources/Views/ALKFormTextItemCell.swift
Sources/Views/ALKGenericCardCell.swift
Sources/Views/KMConversationInfoView.swift
Sources/Views/KMFormDropDownCell.swift
Sources/Views/KMLanguageView.swift
Sources/Views/ListTemplateView.swift

- Added Customisation for dark color for  Conversation Background Color. 
```
Kommunicate.defaultConfiguration.backgroundDarkColor
```
- Added Customisation  for dark color for Conversation Screen Bottom Attachment bar Color. 
```
Kommunicate.defaultConfiguration.chatBarAttachmentViewBackgroundColor
```
- Added Customisation  for dark color Conversation Info Model added parameters with default values. 
```
KMConversationInfoViewModel(infoContent: "This is your conversation info text", leadingImage: leading, trailingImage:trailing, backgroundColor: bg, contentColor: UIColor.white, contentFont:font,darkBackgroundColor: .white, contentDarkColor: .black)
```
- Added Customisation for dark Color for FAQ Customisation. 
```
Kommunicate.kmConversationViewConfiguration.faqDarkBackgroundColor 
``` …

[CM-1459] Dark Mode Support Part -2 

---

CHANGELOG.md
RichMessageKit/Models/SuggestedReplyMessage.swift
RichMessageKit/Views/core/SuggestedReplyView.swift
Sources/Controllers/ALKConversationViewController+TableView.swift
Sources/Controllers/ALKConversationViewController.swift
Sources/Models/ALKMessageModel.swift
Sources/Models/CardTemplate.swift
Sources/Models/ListTemplateModel.swift
Sources/Utilities/ALKMessageViewModel+Extension.swift
Sources/Utilities/ALMessage+Extension.swift
Sources/ViewModels/ALKConversationViewModel.swift
Sources/Views/ALKGenericCardCell.swift
Sources/Views/ALKListTemplateCell.swift

- Added hidePostCTA support for all types of buttons
- Previously when the hidePostCTA was enabled and the user clicked on any suggested reply, the buttons were hiding but a space for that buttons was left behind which is also fixed

[CM-1641] Added hidePostCTA support for different types of buttons

---

CHANGELOG.md
Sources/Controllers/ALKConversationViewController.swift
Sources/Utilities/KMMultipleSelectionConfiguration.swift
Sources/Views/KMFormMultiSelectButtonItemCell.swift
Sources/Views/KMMultiSelectButton.swift

- Calling a reloadIfFormMessage(message: lastMessage, indexPath: indexPath). 
- Fixed the button text hiding issue when selected. Reduced the Size by one unit.
- Fixed the button text touching the border issue. Created the padding.

[CM-1663] Fixed Multiple selection(with new UI) buttons are getting cut in form template 

---

CHANGELOG.md
Sources/Controllers/ALKConversationViewController.swift
Sources/Models/ALKConfiguration.swift
Sources/Models/FormTemplate.swift
Sources/Utilities/ALKMessageViewModel+Extension.swift
Sources/Views/ALKFormCell.swift
Sources/Views/ALKFriendFormCell.swift

- Default configuration added for hiding the form submit button with 'hidePostFormSubmit'.
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/37ed5d38-c659-4171-aa71-58da72782f16

[CM-1706] HidePostFormSubmit | iOS SDK

---

CHANGELOG.md
Sources/Controllers/ALKConversationViewController.swift

- Added support of pre-fill checkboxes on Form Template.
- Updating ALKFormDataCache before the rendering of Form. That allows to show pre-filled data.
1. Just include `"selected": true` in the checkbox options to prefill it.
```
[
{"label":"Male","value":"male","selected":true},
{"label":"Female","value":"female"},
{"label":"Other","value":"other"}
]
```
2. The data of selected Form will be updated only one time in Cache memory at time the form is added first time in message model.
3. When user made Changes in the form new record will be stored in Cache memory.
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/cb9f0107-4dbf-44a3-9c7c-0fb5c13cbdb4
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/cd0b5829-a97b-4fff-b2aa-d57131aede80

[CM-1730] Prefill Checkboxes on Form Template for both UI | iOS SDK

---

CHANGELOG.md
Sources/Views/KMFriendVideoTemplateCell.swift
Sources/Views/KMVideoTemplateCell.swift
Sources/Views/KMYoutubeVideoCell.swift

- Added Support for Youtube Video.
- Added the Message section in Video RM.
- Fixed the height issue coming between Video and timeLable. (when Multiple Video is there)
```
{
"platform": "kommunicate",
"message": "Hello this is example videos",
"metadata": {
"contentType": "300",
"templateId": "14",
"payload": [
{
"url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
"caption": "Video & Youtube Examples"
},
{
"source": "youtube",
"url": "https://www.youtube.com/embed/3-ijFzzF934",
"caption": "Video & Youtube Examples"
}
]
}
}
```
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/b978c0f7-8606-4c68-8c48-2f409fbfc3f1
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/8792691c-a228-4e4a-9f11-bf3ffda6aff …

[CM-1661] Video RM - Youtube embedding 

---

Sources/Controllers/ALKConversationViewController.swift
Sources/ViewModels/ALKConversationViewModel.swift

- Exposed a function to Restrict Agent messaging after 24 hours inactivity for WhatsApp integration.
- Also created a function to get Last Received message.

[CM-1612] Restrict Agent messaging after 24 hours inactivity for WhatsApp integration

---

RichMessageKit/Utilities/UIColor+ExtensionDarkMode.swift
RichMessageKit/Views/core/MessageView.swift
Sources/Controllers/ALKConversationListTableViewController.swift
Sources/Controllers/ALKConversationViewController.swift
Sources/Models/ALKConfiguration.swift
Sources/Utilities/Message+Style.swift
Sources/Utilities/UIColor+Extension.swift
Sources/Views/ALKFriendDocumentCell.swift
Sources/Views/ALKMessageBaseCell.swift
Sources/Views/AutoCompleteManager+TableView.swift
Sources/Views/KMFormDropDownCell.swift

- Added Dynamic color changing support in Form Drop Down.
- Fixed the HTML font setting system default font.
- Added Support of Dynamically Changing Color in HTML Content.
- Added Support of Dynamically Changing Color in HTML Message in Form Payload.
- Created a static variable in UIColor for checking dark Mode is enabled or not. 
- Moved toHexString() in RichMessage as it was not accessible in SPM.
- Now User can enable dark Mode by using this before adding any color configuration in Kommunicate
```
UIColor.isKMDarkModeEnabled = true 
```
- Customisation related to KMStyle user can pass it with `kmDynamicColor`
```
KMStyle(font: .font(.normal(size: 18)), text: UIColor.kmDynamicColor(light: .blue, dark: .purple))
```
- For other Customisation Check this PR : …

[CM-1660] Dark Mode Support Part - 3 (Dynamic Change) 

---

CHANGELOG.md
Sources/Models/ALKConfiguration.swift
Sources/Views/ALKChatBar.swift

- Added Customisation for the line above chatbar.
```
Kommunicate.defaultConfiguration.chatBarToplineViewColor = UIColor.red
```

[CM-1778] Add Color Customization for line above input field 

---

Sources/Controllers/ALKConversationViewController+AutoComplete.swift
Sources/Controllers/AutoCompleteManager.swift
Sources/Models/AutoCompleteItem.swift
Sources/ViewModels/ALKConversationViewModel.swift

Taxbuddy wanted to reassign a conversation back to a bot by using quick replies provided in the dashboard.
We have modified the quickreplies for the same. 
The idea is that they will identify the event at universal webhook and trigger reassignment.
- Provide a way to send specific events along with the quickreplies.
https://github.com/Kommunicate-io/Kommunicate-iOS-AgentApp/assets/139108613/34869634-833c-445a-93ae-3eb82f819844

[CM-1759] Quick Reply implementation for TaxBuddy

---

Sources/Views/ALKLocationCell.swift

- fixed the addressLable coming when there is no geocode.formattedAddress available in viewModel.

[CM-1670] Getting blue while sending location

---

CHANGELOG.md
Sources/LinkPreview/ALKLinkPreviewManager.swift
Sources/Views/ALKLinkPreviewBaseCell.swift

Previously deep link were having previews which should ideally not happen. Now ,only the hyperlinks will have preview option
- Add a url scheme to enable deeplinks inside `Project Settings -> Info -> URL Types`
- Send a message with that deeplink like urlScheme:.//menu
- Verify that there is no link preview for that message

[CM-1792] Fixed link preview showing for deep links

---

Sources/Controllers/ALKDocumentManager.swift
Sources/Models/KMDocumentConfiguration.swift

- Added customisation for Document manager files to be visible to upload.
Note :  Need to `import KommunicateChatUI_iOS_SDK`
- For Customisation 
```
KMDocumentConfiguration.shared.setDocumentOptions(KMDocumentConfiguration.DocumentOptions.some([.docs,.excel, .pdf, .presentation]))
```
- For enabling All
```
KMDocumentConfiguration.shared.setDocumentOptions(KMDocumentConfiguration.DocumentOptions.all)
```

[CM-1828] Expose customisation for Docx and Zips in ALKDocumentManager

---

Sources/Controllers/ALKConversationViewController.swift

- Removed the extra call of `tableView.scrollToRow(at: indexPath, at: .bottom, animated: false)`
- Potential reason of crash as per stack trace received.

[CM-1743] [NSException initWithCoder:]

---

Sources/Controllers/ALKConversationViewController.swift
Sources/Models/FormTemplate.swift
Sources/ViewModels/ALKFormViewModelItem.swift

- Added support of Dialog Flow CheckBox Form.
- https://docs.kommunicate.io/docs/message-types#form-data-using-dialogflow-fulfillment
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/6326a732-9c4f-4c8b-a0c8-6437b0845adf

[CM-1722] Added support of Form data using Dialogflow fulfillment Form 

---

Sources/Resources/Base.lproj/Localizable.strings
Sources/Utilities/Message+Style.swift
Sources/Utilities/SystemMessage.swift
Sources/Views/ALKInformationCell.swift

- Added the new UI to Assigned to Message
- Added localised String for assign to label.
- Added Support of customisation in Assignment Message.

[CM-1853] Assign To message UI Match, Message text

---

Sources/LinkPreview/ALKLinkPreviewManager.swift
Sources/Views/ALKLinkView.swift

- Fixed the Link Preview now it will automatically update the UI when there is change in view.
- Added a check for the URL's to match the correct linkPreviewMeta for the cell's.
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/90a58674-23c7-4e01-9cd0-cb12a6508eff
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/f9487bcd-1602-40bf-a4a8-64f420fd175c

[CM-1834] Link preview for 2nd last message is being overridden by last msg

---

Sources/Views/ALKChatCell.swift

- Fixed assignee image is not getting rendered on conversation list when it is created with title.
- Instead placeholder image is getting rendered.

Fixed assignee image is not getting rendered on conversation list when it is created with title

---

CHANGELOG.md
Demo/Podfile.lock
KommunicateChatUI-iOS-SDK.podspec

- Added the last Message icon in Conversation List Screen.
- Fixed Link preview issue. 
- Fixed Assignee Image not showing with custom title.

Updated ChatUI PodFile to 1.2.9

---

Sources/Utilities/ALMessage+Extension.swift
Sources/Views/ALKChatCell.swift

- Added in protocol to fetch the tags assigned to the conversation.

[CM-824] Show tags on conversation list same as that on dashboard | iOS Agent App 

---

Sources/Views/ALKFriendMessageCell.swift
Sources/Views/ALKMessageBaseCell.swift

- Added support for Iframe Contents.

[CM-1959] Iframe Support for HTML Content 

---

Sources/Utilities/Message+Style.swift

- Changed color of send message text color to white previously it was black. 
- Previously the color is updated when we call this function `Kommunicate.setup(applicationId: applicationId)`.

Changed Default Text Color of send message to white.

---

Sources/Controllers/ALKConversationViewController.swift
Sources/Models/ALKChatBarConfiguration.swift
Sources/ViewModels/ALKConversationViewModel.swift
Sources/Views/ALKChatBar.swift

- Added Customisation to hide attachment options when bot is replying to the conversation.
- Customisation Code :  `Kommunicate.defaultConfiguration.chatBar.hideAttachmentOptionsForBotConvesations = true`
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/069a8f4c-597b-4fc2-b626-0db452f8b2ef

[CM-1453] Expose a function to show/hide attachment options

---

Sources/Utilities/ALKAppSettingsUserDefaults.swift
Sources/Utilities/Message+Style.swift

- Updated sent message Colour. Previously the color was `0xF1F0F0` now `0x5553B7`
- added default value of `csatRatingBase` to 3. Creating issue when that is not available in AppSetting Api Call.

Fixed Sent Message Colour issue

---

Sources/Utilities/ALMessage+Extension.swift
Sources/Utilities/Date+Extension.swift

- Time label for messages are updated to 12hr format from 24hr format.
- In conversation screen date label is added with Year as well.

[CM-2048] Time, Date Format on conversation screen similar to Android & Web

---

Sources/Models/ALKConfiguration.swift
Sources/Utilities/ALKPushNotificationHandler.swift

- Added Customisation to update color of in App Banner. Customisation is accessible for Background Color, Title Color, Content Color.
```
Kommunicate.defaultConfiguration.inAppBannerColor = UIColor.kmDynamicColor(light: .systemBrown, dark: .systemBlue)
Kommunicate.defaultConfiguration.inAppBannerTextColor = UIColor.kmDynamicColor(light: .white, dark: .black)
Kommunicate.defaultConfiguration.inAppBannerContentColor = UIColor.kmDynamicColor(light: .white, dark: .black)
Kommunicate.defaultConfiguration.inAppBannerRadius = 12
Kommunicate.defaultConfiguration.inAppBannerShadowRadius = 15
Kommunicate.defaultConfiguration.inAppBannerOpacity = 0.5
Kommunicate.defaultConfiguration.inAppBannerShadowColor = UIColor.kmDynamicColor(light: .black, dark: .red)
``` …

[CM-1827] In App Notification Banner Colour Customization

---

Sources/Controllers/ALKConversationViewController+TableView.swift
Sources/Controllers/ALKConversationViewController.swift
Sources/Resources/Base.lproj/Localizable.strings
Sources/Utilities/SystemMessage.swift
Sources/ViewModels/ALKConversationViewModel.swift
Sources/Views/KMFriendSourceURLViewCell.swift

- Added a new view for Source URL.
```
"sourceURLs" = ["https://dashboard.kommunicate.io", "https://docs.kommunicate.io"]
```

[CM-2072] Show answer source url with bot answer 

---

Sources/Controllers/ALKConversationViewController.swift
Sources/ViewModels/ALKConversationViewModel.swift

- Added a check for `AL_DELETE_GROUP_MESSAGE_FOR_ALL` to remove conversation from DB.
- Added a notification for message metadata update and a check for Message Delete.
- Deleting the message from local DB as well for remove the chance of indexing error in Message Table.
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/81c086ad-c5a9-4f87-ae3d-7d0fefcb884a

[CM-1121] Delete message with sync - iOS Agent App and SDK

---

Sources/Controllers/ALKConversationViewController.swift

- Updated the code of configure chat bar code.
- Moved the check for restricted conversation bellow the other checks. 
- Used the existing function for checking the restrictions.

[CM-2111] Crash : closure #1 in ALKConversationViewController.configureChatBar() | iOS Agent App

---

Sources/Views/KMFriendSourceURLViewCell.swift
Sources/Views/KMLabelWithIconView.swift

- Added Link Icon in the End of Each Source URL Text. 
- Added a Code to Check if the title is not present in recived payload then it will use that for Title other wise it will extract the data from the URL.
- Added a code to extract the last text of URL. (For eg. : if URL is "https://www.apple.com/in/iphone-15/" it will extract "iphone-15" ) 
- Updated the code to extract object from string.( For eg: The code will also work if data is like this
```
answerSource = "[{\"name\":\"Kommunicate\",\"url\":\"https://dashboard.kommunicate.io/conversations/104283232\"},{\"name\":null,\"url\":\"https://dashboard.kommunicate.io/conversations/104243900\"},{\"name\":null,\"url\":\"https://dashboard.kommunicate.io\"},{\"name\":null,\"url\":\"https://dashboard.doc.io/\"}]"
```
- Added Underline in the …

[CM-2145] Source URL UI and Flow Update | iOS SDK

---

Sources/Controllers/ALKConversationViewController.swift

- Added a placeholder identification check for autosuggestion message and adding the placeholder text on refresh of viewController.
https://github.com/user-attachments/assets/5c51c919-900d-4c9b-8f6d-f3d0ce604e6c
https://github.com/user-attachments/assets/41770b56-0804-4c60-a542-4ba30dd15864

[CM-1836] Placeholder is getting refreshed on Bot delay| iOS SDK 

---

CHANGELOG.md
Demo/Podfile.lock
KommunicateChatUI-iOS-SDK.podspec
Package.resolved
Package.swift

- Updated the Zendesk Version for the issue of `Enabled BitCode` while pushing app to AppStore.
- Updated PodFile to 1.3.5

Updated Podfile to 1.3.5

---

Sources/Controllers/ALKConversationViewController.swift
Sources/Models/ALKChatBarConfiguration.swift

- Added a customisation to hide chat bar when bot is handling the conversation and enable chat bar when conversation is assigned to human.
- `Kommunicate.defaultConfiguration.chatBar.hideChatBarForBotConvesations = true`
https://github.com/user-attachments/assets/ed38888e-6694-4f58-9890-890004327066

[CM-2195] Hide Chat Bar - Customization | iOS SDK

---

Sources/Controllers/ALKConversationViewController.swift
Sources/ViewModels/ALKConversationViewModel.swift

- Suspecting the crash occurs when the conversation screen is loading messages for the first time via the API, and the typing indicator is triggered simultaneously. An additional check is needed on the agent app side, as the typing indicator also appears for the welcome message on the SDK side.

[CM-2070] Crash: ConversationListViewModel.updateTypingStatus(in:userId:status:) | iOS Agent App

---

Sources/Controllers/ALKConversationViewController+TableView.swift
Sources/Controllers/ALKConversationViewController.swift
Sources/ViewModels/ALKConversationViewModel.swift

- Added a check to identify the End User UserId. Used to identify the message received from where. This is required only for agent app for that added a check to only call the function when the agent app is enabled.
- Added colour for received message from bot or agent, End User or sent Message.

[CM-702] Conversation Section Colour Improvements | iOS Agent App

---

KommunicateChatUI-iOS-SDK.podspec
Sources/Controllers/ALKConversationViewController.swift
Sources/Utilities/KMZendeskChatHandler.swift
Sources/ViewModels/ALKConversationViewModel.swift

- Moved Zendesk Plugin to optional State. 
- For Including Zendesk SDK need to add it like 'Kommunciate/Zendesk'
- Zendesk Code in SDK is optional until the package is included it will not be accessible.
- With Zendesk 
```
use_frameworks!
platform :ios, '13.0'
target 'MyTargetName' do
pod 'Kommunicate/Zendesk'
end
```
- Without Zendesk
```
use_frameworks!
platform :ios, '13.0'
target 'MyTargetName' do
pod 'Kommunicate'
end
```

[CM-2232] Zendesk Plugin Removal | iOS SDK
