CHANGELOG.md, KommunicateChatUI-iOS-SDK.podspec
=> Release - 0.1.0

Sources/Views/StoryBoards/ALKDateSectionHeaderView.xib, Sources/Views/StoryBoards/EmptyChatCell.xib
some xib files are not linked with the KM Chat ui. it creates crashes in KM SDK
Tested locally by linking those files to KM Chat UI
=> Link XIB files with KM Chat UI 

Demo/KommunicateChatUI-iOS-SDK-Demo.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Demo/Podfile.lock, Sources/Controllers/ALKConversationViewController.swift, Sources/ViewModels/ALKConversationViewModel.swift
- Bot Typing Indicator based on delayTime value from the dashboard
=> [CM-701] Bot Typing Indicator

Demo/Podfile, Demo/Podfile.lock, Sources/Controllers/ALKConversationListViewController.swift, Sources/Controllers/ALKConversationViewController.swift
Added listener callback to get Away/Online(APPLOZIC_25) status change in  realtime
Locally tested by using the callback
=> [CM-758] Added a callback to get realtime update of user away online status

Sources/CustomEvent/CustomEvent.swift
Added resolve event in the custom event list.
Locally tested by triggering the event.
=> [CM-830] Add Conversation Resolve Event Listener | iOS SDK

CHANGELOG.md, RichMessageKit/Views/ReceivedButtonsCell.swift, RichMessageKit/Views/ReceivedFAQMessageCell.swift, RichMessageKit/Views/ReceivedImageMessageCell.swift, Sources/Models/ALKConfiguration.swift, Sources/Utilities/KMCellConfiguration.swift, Sources/Views/ALKFriendDocumentCell.swift, Sources/Views/ALKFriendFormCell.swift, Sources/Views/ALKFriendGenericCardMessageCell.swift, Sources/Views/ALKFriendLinkPreviewCell.swift, Sources/Views/ALKFriendLocationCell.swift, Sources/Views/ALKFriendMessageCell.swift, Sources/Views/ALKFriendMessageQuickReplyCell.swift, Sources/Views/ALKFriendPhotoCell.swift, Sources/Views/ALKFriendVideoCell.swift, Sources/Views/ALKFriendVoiceCell.swift, Sources/Views/ALKMessageButtonCell.swift
- Adding customisation to hide the sender Name in the Conversation | iOS SDK
=> [CM-859] Add A customisation Option to hide the sender Name in the Conversation | iOS SDK

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- upgraded KMCore pod to 1.0.3
- changed chatUI pod version to 0.2.2
=> Upgrade of KMCore Version to 1.03

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- updated chat ui version to 0.2.3
- 0.2.2 tag was created long before with KMCellconfiguration issue & its causing problem in release of this pod
=> updated KM Chat uI version to 0.2.3

Sources/ViewModels/ALKConversationViewModel.swift
- Added a computer property to get conversation created date to use it on User Info Screen
=> [CM-925] Added a property to get Created time of the conversation

Sources/Controllers/ALKConversationViewController.swift, Sources/Utilities/Message+Style.swift, Sources/Views/ALKInformationCell.swift
- Fixed Message not reflecting in realtime in agent app
- Fixed information messagenot reflecting issue. Only Feedback were showing in the conversation, not informations like  assignment,resolve,reopen events.
- Fixed Rating View issue in agent app
- These are not production issues. live app is working fine.
=> [CM-1031] Fixed Message Real time updation issue in agent app

CHANGELOG.md, Sources/Controllers/ALKConversationViewController.swift, Sources/Models/ALKConfiguration.swift, Sources/Utilities/KMTextToSpeech.swift, Sources/Utilities/KMTextToSpeechHandler.swift, Sources/ViewModels/ALKConversationViewModel.swift
- Text To Speech (TTS) for message in the conversation
- Added settings to enable/ disable it. By default it will be disabled
=> [CM-1015] Text To Speech Feature

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
=> Updated Version to 0.2.5

Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Sources/Controllers/ALKConversationViewController.swift, Sources/Utilities/UITableView+Extension.swift
- Auto Scroll is not working inside the conversation screen
Bug/Issue:
https://user-images.githubusercontent.com/61688116/182324602-07f65edf-07c9-49c3-86ce-a5b96077aea0.mov
After Fixing it:
https://user-images.githubusercontent.com/61688116/182324595-e0655b49-91da-4955-8c45-58c174812a5d.mov
=> [CM-1035] Auto Scroll is not working in the conversation

CHANGELOG.md, Sources/Views/ALKFormCell.swift, Sources/Views/ALKFriendFormCell.swift
- Fixed Form Cell height issue for iPhone 6
- Fixed Form Submit Button Width going beyond screen width issue
=> [CM-989] Fixed Form Cropping issue for iPhone 6

CHANGELOG.md, Sources/Controllers/ALKBaseViewController.swift, Sources/Models/ALKConfiguration.swift
- Added Customisation for hiding Navigation bar in ALK, KM ViewControllers
-  Added flag for EmbeddedViewController Name. This configuration is to Stop In App Notification when user is in Embedded VC.
=> [CM-1070] Added customization for hiding navigation bar 

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift
- Updated KM Core pod to 1.0.5
- Updated KM Chat UI version to 0.2.6
- Updated Changelog
=> Updated KM Core & KM ChatUI version

CHANGELOG.md, Sources/CustomEvent/CustomEvent.swift
- Added Events for message receive, Back press on Conversation & Conversation list screen
=> [Cm-1135] Added new events for message received,back button tap

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift
- upgraded KM Core to 1.0.6
- update KM Chat UI Version to 0.2.7
=> release changes

Demo/KommunicateChatUI-iOS-SDK-Demo.xcodeproj/project.pbxproj, Demo/Podfile, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Sources/Controllers/ALKConversationViewController.swift, Sources/Utilities/KMZendeskChatHandler.swift, Sources/ViewModels/ALKConversationViewModel.swift
- Created a class KMZendeskChatHandler to handle all zendesk flow
- Added Zendesk pods as sub pods of KM Chat UI
=> [CM-1189] Zendesk Integration

CHANGELOG.md, Demo/Podfile, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift
- upgraded version to 0.2.8
- updated the changelog
=> Upgraded pod version to 0.2.8

Sources/Models/ALKConfiguration.swift
- Added Flag to customize visibility of the start new button at the bottom
=> Added flag to hide the bottom start new conversation button

CHANGELOG.md, Sources/CustomEvent/ALKCustomEventHandler.swift
- Added a function to unsubscribe events.
=> Added support for unsubscribe to events

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- upgraded version to 0.2.9
- updated changelog
=> Upgrade  version to 0.2.9

CHANGELOG.md, Sources/Models/ALKConfiguration.swift
- Added customisation to show or hide the Restart Conversation Button on conversation screen
=> [CM-1308] Added customisation for Restart Conversation  button

CHANGELOG.md, Sources/Models/ALKConfiguration.swift
- Added a flag to customise the back button on conversation list screen
=> [CM-1302] Added a flag to customise back button on conversation list screen

Sources/Controllers/ALKConversationListViewController.swift, Sources/Controllers/ALKConversationViewController+MessageCell.swift, Sources/Controllers/ALKConversationViewController.swift, Sources/Controllers/ALKCreateGroupViewController.swift, Sources/Controllers/ALKCustomCameraViewController.swift, Sources/Controllers/ALKCustomVideoCaptureController.swift, Sources/Controllers/ALKNewChatViewController.swift, Sources/Controllers/ALKParticipantSelectionViewContoller.swift, Sources/Utilities/UI+Style.swift, Sources/Utilities/UIAlertController+Extension.swift, Sources/Utilities/UIApplication+Extension.swift, Sources/Utilities/UIViewController+Extension.swift, Sources/Views/ALKChatBar.swift, Sources/Views/ALKChatCell.swift, Sources/Views/ALKLinkPreviewBaseCell.swift, Sources/Views/ALKLocationCell.swift, Sources/Views/ALKMyGenericCardMessageCell.swift, Sources/Views/AudioRecordingView.swift, Sources/Views/TypingNoticeView.swift
- Added Support for App-extensions
- calling `UIApplication.shared` directly is not supported in App extensions. Added UIApplication+Extension file
=> [CM-1180] Added Support for App-Extension

Sources/Controllers/ALKConversationViewController.swift, Sources/CustomEvent/ALKCustomEventCallback.swift, Sources/CustomEvent/ALKCustomEventHandler.swift
- Added support for list, card template button clicks for event callbacks
- Fixed typo in parameter name
=> Added List, Card Event click in RichMessage Event callback

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- upgraded version to 0.3.0 
- updated changelog
=> Upgraded pod version to  0.3.0

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- upgraded version to 0.3.1
- updated chagelog
=> upgraded version to 0.3.1

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Updated the pod version to 1.0.0
- Updated the changelog
=> Updated the  pod version to 1.0.0

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Upgraded KM Chat UI to 1.0.1
=> Upgraded Pod version to 1.0.1

CHANGELOG.md, Demo/Podfile, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift
- Upgraded KM Core to 1.0.8
- Updated pod version to 1.0.2
- updated changelog
=> updated pod version to 1.0.2 & upgraded KM Core to 1.0.8

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Updated Pod version to 1.0.3
- updated chagelog file
=> Upgrade pod version to 1.0.3

CHANGELOG.md, Sources/Controllers/ALKConversationViewController.swift, Sources/ViewModels/KMConversationInfoViewModel.swift, Sources/Views/KMFormMultiSelectButtonItemCell.swift, Sources/Views/KMMultiSelectButton.swift
- Fixed Conversation tap issue
- Fixed SPM Build issue
=> Fixed conversation info tap issue

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Updated pod version to 1.0.4
- updated changelog file
=> Updated pod version

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Updated pod version to 1.0.5
- Updated changelog
=> Upgrade pod version 1.0.5

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Upgraded Pod version to 1.0.7
- Updated Changelog
-
=> Upgraded Pod version to 1.0.7

Sources/Utilities/KMZendeskChatHandler.swift
- Fixed Zendesk Connection issue which causes handoff failure
- Added api to track the failure cases of handoff, message delivery to zendesk
=> fixed Socket connection issue

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift, Sources/Utilities/KMZendeskChatHandler.swift
- Updated Pod version to 1.0.8
- Fixed build issued
=> updated pod spec & chang log entry. fixed build issue

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Updated Chat UI pod version to 1.0.9
- Added changelog entry
=> Updated pod version to 1.0.9 & added changelog entry

Demo/KommunicateChatUI-iOS-SDK-Demo.xcodeproj/project.pbxproj, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift, Sources/Controllers/ALKConversationViewController.swift, Sources/Models/FormTemplate.swift, Sources/ViewModels/ALKFormViewModelItem.swift, Sources/Views/ALKFormCell.swift, Sources/Views/KMFormDropDownCell.swift
- Added Support for DropDown field on Form Template
- Added customisation for height, row height, list height, arrow size,arrowcolor,selectedcolorbackground, default background.etc.
##SS
=> [CM-684] Added Support for Drop down template in Form

CHANGELOG.md, Sources/Models/ALKNavigationItem.swift
- Added Support for text, background customisation for FAQ button 
```
Kommunicate.kmConversationViewConfiguration.faqTextColor = .cyan
Kommunicate.kmConversationViewConfiguration.faqBackgroundColor = .black
```
=> [CM-1490] Updated FAQ as  Button UI.Added customisation for text, background

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Updated pod version to 1.1.0 and added changelog entry
=> updated pod version to 1.1.0

CHANGELOG.md, Demo/Podfile.lock, Sources/Resources/Base.lproj/Localizable.strings, Sources/Utilities/ALMessage+Extension.swift
- Matched Last Message listerals on Conversation List screen with Android SDK
=> [CM-1237] Matched last message on conversation list screen

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Updated pod version to 1.1.1
=> updated pod version to 1.1.1

Sources/Controllers/ALKConversationViewController.swift
- Expose Method to populate text on chat bar
=> [CM-1434] Added support for updating chat bar text 

CHANGELOG.md, Package.swift
- Added name for iOSDropDown package 
- Added iOSDropDown package in target
=> [CM-1534] Fixed SPM build issue due to Dropdown dependency 

CHANGELOG.md, Demo/Podfile.lock, Sources/Controllers/ALKConversationViewController.swift
- Fixed form submission with empty fields issue 
- After validating, we are doing unnecessary check thats creating a scenario all form fields should be filled to do submit the form which creates a problem when user give optional fields to fill.
- Removed above check
=> [CM-1496] Fixed Form Submission with empty fields issue

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Updated the SDK version to 1.1.2
- Added a changelog entry
=> Updated the ChatUI to 1.1.2

Sources/Controllers/ALKConversationViewController.swift
- Fixed event action data issue for List template
- Fixed event action data issue for button clicks
=> Fixed event action data issue

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift
- upgraded core sdk to 1.1.1
- added a changelog entry
=> Added files & upgraded core sdk

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Improved UI of multiple language selection & make it similar to android
- Refresh Icon Change
=> upgraded pod version to 1.1.4

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Crash fix for agent app while updating it to latest IOS SDK
=> upgraded pod version to 1.1.5

CHANGELOG.md, Sources/Controllers/ALKConversationViewController.swift, Sources/Models/FormTemplate.swift, Sources/Views/ALKFormCell.swift, Sources/Views/KMFormDropDownCell.swift
You can use the below payload for form type rich message, more can be found [here](https://docs.kommunicate.io/docs/message-types#form-with-dropdown-list)
```
{
"platform": "kommunicate",
"message": "Form Dropdown - Template 1",
"metadata": {
"templateId": "12",
"contentType": "300",
"payload": [
{
"type": "dropdown",
"data": {
"options": [
{
"value": "Engineer",
"label": "Engineer"
},
{
"value": "entrepreneur",
"label": "Entrepreneur"
},
{
"label": "Doctor",
"value": "Doctor"
},
{
"value": "Lawyer",
"label": "Lawyer"
},
{
"value": "Lawyer",
"label": "Lawyer"
},
{
"value": "Lawyer",
"label": "Lawyer"
},
{
"value": "Lawyer",
"label": "Lawyer"
},
{
"selected": true,
"disabled": true,
"label": "Select"
}
],
"title": "Your Profession",
"name": "profession",
"validation": {
"errorText": …
```
=> [CM-1409] Added validation and default value to a form type rich message

Sources/Views/KMLanguageView.swift
- Fixed SPM build issue due to KMLanguageView
=> spm build issue

Sources/Views/KMLanguageView.swift
- Fixed build issue due to KMLanguageView
=> Pod build issue due to KMLanguageView

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
=> upgraded chat ui to 1.1.6

CHANGELOG.md, Sources/Controllers/ALKConversationViewController.swift
- Moved prepareMoreBar inside the if block and checked if moreBar.isHidden.
=> [CM-1562] Fixed crash CustomConversationVC.viewWillAppear(_:) | iOS SDK

Sources/Controllers/ALKConversationViewController+TableView.swift, Sources/Controllers/ALKConversationViewController.swift, Sources/Models/ALKMessageModel.swift, Sources/Models/VideoTemplate.swift, Sources/Utilities/ALKMessageViewModel+Extension.swift, Sources/Utilities/ALMessage+Extension.swift, Sources/ViewModels/ALKConversationViewModel.swift, Sources/Views/KMFriendVideoTemplateCell.swift, Sources/Views/KMMyVideoTemplateCell.swift, Sources/Views/KMVideoCell.swift, Sources/Views/KMVideoTemplateCell.swift
- Added support for Video Rich Message with URL
```
{
"platform": "kommunicate",
"message": "Hello this is example videos",
"metadata": {
"contentType": "300",
"templateId": "14",
"payload": [
{
"url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
"caption": "Video & Youtube Examples"
}
]
}
}
```
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/121929127/de1ec262-e46d-47cf-a367-f833a4381151
=> Added support for Video Rich Message with url

Sources/Views/KMVideoTemplateCell.swift
- Fixed caption is cutting in UI issue
=> Fixed height issue

Sources/Views/KMFriendVideoTemplateCell.swift
- added kingfisher tag in KMFriendVideoTemplateCell
=> Added kingfisher mark

RichMessageKit/Utilities/UIColor+ExtensionDarkMode.swift, Sources/Utilities/UIColor+Extension.swift
- Moved dynamicColor function to RichMessage.
=> Release fix for Dynamic Color Function

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift, RichMessageKit/Utilities/UIColor+ExtensionDarkMode.swift, Sources/Utilities/UIColor+Extension.swift
- Added the pod changes.
- Moved the Dynamic Color Function in RichMessage.
=> Added the Fix for Dynamic Colour Function

Sources/Controllers/ALKConversationViewController.swift
- Created a fcuntion to hide chat bar to support restrictoperatortoreadonly settings
=> Team Concept part 2

RichMessageKit/Views/core/SuggestedReplyView.swift
- Fixed the spacing issue in two buttons.
=> Fixed Spacing of two suggestion button 

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift
=> Updated podfile to 1.2.0

CHANGELOG.md, RichMessageKit/Utilities/UIColor+ExtensionDarkMode.swift, RichMessageKit/Views/ReceivedButtonsCell.swift, Sources/Controllers/ALKConversationListTableViewController.swift, Sources/Controllers/ALKConversationViewController.swift, Sources/Views/ALKChatBar.swift, Sources/Views/ALKMessageButtonCell.swift
- Fixed iOS 17 BUtton issue.
- Fixed the Typing Customization issue.
- Disabled dark Mode.
=> [CM-1715] iOS 17 issue for Rm Buttons , Disable Dark Mode

Sources/Controllers/ALKConversationViewController.swift
- Fixed MultiSelected Option not showing in Post Form Message.
=> Fix Multi Selected Form Post Reply Message

Sources/Controllers/ALKConversationViewController.swift, Sources/ViewModels/ALKConversationViewModel.swift
- Fixed the issue of upload.
- Fixed the issue of conversation Mismatch.
=> fix for upload attachment crash and conversation Mismatch

Sources/ViewModels/ALKConversationViewModel.swift
- Fixed the message delete issue. when payload is not having message or any attachment is sent from dashboard without message.
=> fixed Message delete issue when payload is not having message.

Sources/Utilities/ALKMessageViewModel+Extension.swift, Sources/ViewModels/ALKConversationViewModel.swift
=> fix for delete of message in hidePostCTA

CHANGELOG.md, Sources/Controllers/ALKConversationViewController.swift
- Restricted agent reply for zendesk conversation
=> [CM-1737] Restricted agent reply for zendesk conversation

RichMessageKit/Models/Message.swift, Sources/Controllers/ALKConversationViewController+TableView.swift, Sources/Controllers/ALKConversationViewController.swift, Sources/Models/ALKMessageModel.swift, Sources/Utilities/ALMessage+Extension.swift, Sources/ViewModels/ALKConversationListViewModel.swift, Sources/ViewModels/ALKConversationViewModel.swift, Sources/Views/KMTypingIndicator.swift
- Added New UI For Typing Indicator 
- Replaced the function with new Function for new typing indicator.
- Created the code for adding and deleting typing indicator to messageModel and alMessage.
- New Typing indicator is a message type added in message model and considered as message in conversation Screen. 
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/2ee348ab-f835-4c1e-9ddb-8aa6c9a296d2
=> [CM-1374] Typing Indicator

Sources/Views/ALKFormCell.swift, Sources/Views/KMFormDropDownCell.swift
- Fixed the default selection issue in dropDown. 
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/994f7e04-8374-47cc-a1f5-816bddc969a6
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/c1c14b69-3240-41a6-ab87-29990365da96
=> Updated the code for saving the default selection data in dropDown

Sources/CustomEvent/ALKCustomEventCallback.swift, Sources/CustomEvent/ALKCustomEventHandler.swift, Sources/CustomEvent/CustomEvent.swift
- Added support for event callback for resolve event
- Tested for normal conversation resolve event
- Tested for Zendesk Conversation resolve event from by ending the chat from zendesk dashboard
=> Added support for resolve conversation event calback

RichMessageKit/Views/ReceivedFAQMessageCell.swift, RichMessageKit/Views/ReceivedImageMessageCell.swift, RichMessageKit/Views/SentButtonsCell.swift, RichMessageKit/Views/SentFAQMessageCell.swift, RichMessageKit/Views/SentImageMessageCell.swift, Sources/Views/ALKFriendFormCell.swift, Sources/Views/ALKFriendGenericCardMessageCell.swift, Sources/Views/ALKFriendMessageQuickReplyCell.swift, Sources/Views/ALKListTemplateCell.swift, Sources/Views/ALKMyFormCell.swift, Sources/Views/ALKMyGenericCardMessageCell.swift, Sources/Views/ALKMyMessageQuickReplyCell.swift
- Fixed Message Reusable cell issue
=> Updated the code for messageViewUpdate for iOS 17

Sources/ViewModels/ALKConversationViewModel.swift
- Fixed the form cut issue by calling messageUpdate at delay of 0.3 s after form message is added.
=> Fixed new form UI getting Cut issue

Sources/Views/ALKFormCell.swift
Fixed crash on dropdown on below payload for default selection
```
{
"platform": "kommunicate",
"message": "Form Dropdown - Template 1",
"metadata": {
"templateId": "12",
"contentType": "300",
"payload": [
{
"type": "dropdown",
"data": {
"options": [
{
"value": "Engineer",
"label": "Engineer"
},
{
"value": "entrepreneur",
"label": "Entrepreneur"
},
{
"label": "Doctor",
"value": "Doctor"
},
{
"value": "Lawyer",
"label": "Lawyer"
},
{
"selected": true,
"disabled": true,
"label": "Select"
}
],
"validation": {
"errorText": "Please select your profession"
},
"title": "Your Profession",
"name": "profession"
}
},
{
"type": "text",
"data": {
"placeholder": "Enter your name",
"label": "Name"
}
},
{
"data": {
"name": "Submit",
"type": "submit",
"action": {
"message": "optional- this message will be …
```
=> fixed crash on dropdown

Sources/Controllers/ALKConversationViewController.swift
- Updated the Constraints for send button. These constraints are used in agent app for restricting Chat Bar.
=> [CM-1875] Fixed specialized ConversationListViewController.tapped(_:at:) 

Sources/Views/ALKFriendMessageQuickReplyCell.swift
- Made the cell visible for all the suggested reply message.
=> [CM-1918] Fixed Not able to render suggested replies sometimes

Sources/ViewModels/ALKConversationViewModel.swift, Sources/Views/ALKFriendFormCell.swift
- Form Submit Button Text is not updating because the submit button is not appending in the submit button superView.
- Fixed the form rendering issue. 
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/009d6189-22f9-46a8-aacb-9ecb313b5c60
https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/assets/139110221/6cdd03d3-aecc-470f-a7b8-20f577943abe
=> Fixed form submit button tittle issue and Rendering issue of Form

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Upgraded KM Chat UI to 1.2.8
- Updated the changelog
=> Upgraded Chat UI 1.2.8

Sources/Controllers/ALKConversationViewController+TableView.swift
- Fixed crash issue due heightForRow function
- There is a possibility to outofbound exception
- Not able to reproduce the issue
=> Fixed crash issue due heightForRow function

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Improved read receipt label for messages.
- Fixed crash issue due heightForRow function
=> Updated chatUI pod File to 1.3.0

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift
- Updated Change log.
- Updated KM Core to 1.1.9
- Updated KM ChatUI to 1.3.1
=> Updated pod to 1.3.1

Sources/Views/ALKFormCell.swift, Sources/Views/ALKFormDateItemCell.swift, Sources/Views/ALKFormPasswordItemCell.swift, Sources/Views/ALKFormTextItemCell.swift, Sources/Views/KMFormDropDownCell.swift
- Updated the UI of Form Text Field.
=> [CM-1543] Improve the Form Text Field or Text Area UI Similar to Web, Android in iOS SDK

Sources/Controllers/ALKConversationViewController.swift
- Removed Send Button Form Layout when the Conversation is restricted.
- Used perform without animation function to update the UI.
- Added a Check when the value is changed only then the UI for Chat Bar Will be Updated.
=> [CM-2069] Crash : specialized ConversationListViewController.tapped(_:at:) | iOS Agent App

Sources/Models/ALKConfiguration.swift, Sources/Utilities/ALKPushNotificationHandler.swift
Reverts Kommunicate-io/KommunicateChatUI-iOS-SDK#295
Tap Gesture not working
=> Revert "[CM-1827] In App Notification Banner Colour Customization"

Sources/Controllers/ALKConversationViewController.swift
- Moved the code in main thread as some time this function is called from the background thread.
=> [CM-2095] Crash : CustomConversationVC.refreshViewController() | iOS Agent App

Sources/Models/ALKConfiguration.swift
- Added a configuration to disable root detection.
=> [CM-2165] Jailbreak Detection | iOS SDK & Agent App

Sources/Utilities/ALMessage+Extension.swift
- Added a check for content type for setting isMyMessage.
=> added a check for the contentType for isMyMessage

Sources/Models/ALKChatBarConfiguration.swift, Sources/Views/ALKLocationCell.swift, Sources/Views/ALKMessageBaseCell.swift, Sources/Views/ALKReplyMessageView.swift
- Added Suggestion for adding Google Api Key when adding location in chat bar.
- Added print statement in console when ever api key is found missing in project.
=> [CM-2178] Google API keys leakage | iOS SDK

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Updated Pod Version from `1.3.5` to `1.3.6`
=> Updated PodFile to 1.3.6

Sources/Resources/Base.lproj/Localizable.strings, Sources/Utilities/Message+Style.swift, Sources/Utilities/SystemMessage.swift, Sources/Utilities/UIView+Extension.swift, Sources/Views/ALKInformationCell.swift, Sources/Views/KMTextViewPopUP.swift
- Added Summary UI for iOS Agent App for conversation screem. 
- The View contains a Universal PopUp View. It's a reusable component for showing large size content.
https://github.com/user-attachments/assets/8c9299df-2889-4e17-8b47-166845b4bb59
=> [CM-2210] Summary UI | iOS Agent App

RichMessageKit/Utilities/QuickReplyConfig.swift, Sources/Utilities/ReceivedMessageCaptionViewSizeCalculator.swift, Sources/Views/KMVideoCell.swift, Sources/Views/KMVideoTemplateCell.swift, Sources/Views/KMYoutubeVideoCell.swift
- Updated the Caption Label View.
- Added the method to extract the height of the cation view.
- Adding the value of caption screen height to the main height.
=> Caption cutting in Video Rich Message | iOS SDK 

Sources/Controllers/KMAutoCompleteManager.swift, Sources/Views/KMVideoCell.swift
- Added Identifier for Automation. ( Video Cell & AutoSuggestion )
=> [CM-2219] Automation in Rich message | iOS SDK

CHANGELOG.md, Demo/KommunicateChatUI-iOS-SDK-Demo.xcodeproj/project.pbxproj, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift
- Fixed an issue where captions were cut off in Video Rich Messages.
- Made the Zendesk Plugin optional for integration flexibility.
- Added a new feature to collect email addresses in Away Mode.
=> Updated Pod 1.3.8

Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Updated pod version to 1.3.8
=> Updated Pod version form 1.3.7 to 1.3.8

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Updated the release version to 1.3.8
=> Release 1.3.8

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift
- Updated Pod version of Core to 1.2.5
- Updated SDK Version to 1.3.9
=> Updated PodFile to 1.3.9 

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec
- Updated SDK Version to 1.4.0
=> Updated PodFile to 1.4.0

Sources/Controllers/ALKConversationViewController.swift
- Added Identifier for More Button.
=> [CM-2344] Add 4 Automation test Case | iOS SDK

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift
=> Updated PodFile to 1.4.2

Sources/Controllers/ALKConversationViewController.swift
- Updated the value for collectEmailOnAwayMode on reopening of old conversation or creation of new conversation.
=> Added the fix for collectEmailUI bug

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift
=> Updated Podfile to 1.5.0

CHANGELOG.md, Demo/Podfile.lock, KommunicateChatUI-iOS-SDK.podspec, Package.resolved, Package.swift
- Form UI Customisation Added.
- Video Preview Inhancement.
- Subscription requirement Message Box Updated.
- Bug Fixes.
- Caption Support in Video.
- Pod file update to 1.5.1
=> Pod Update to 1.5.1
